/*批次流水號編制步驟範例*/
DECLARE @MAXNO	VARCHAR(5)
/*1.從資料表取最大流水號*/
SELECT @MAXNO=ISNULL(MAX(SERIAL),'00000') FROM STOCK_NAME_SERIAL
PRINT '目前最大號:'+@MAXNO

/*2.宣告流水號編制暫存資料表*/
DECLARE @SERIAL	TABLE
(
	AUTOID	INT IDENTITY,--自動流水號
	SYMBOL	VARCHAR(10),--股票代號
	SERIAL	VARCHAR(5) NULL--流水號
)

/*3.將需編號的紀錄新增至暫存資料表*/
INSERT @SERIAL (SYMBOL) SELECT SYMBOL FROM STOCK_NAME_FULL ORDER BY SYMBOL

/*4.使用IDENTITY 欄位取得遞增序號 */
UPDATE @SERIAL SET SERIAL=CONVERT(VARCHAR(5),AUTOID+CONVERT(INT,@MAXNO))

/*5.將流水號補足固定長度*/
UPDATE @SERIAL SET SERIAL=RIGHT('00000'+SERIAL,5)

SELECT * FROM @SERIAL

/*6.將流水號由暫存檔更新回主資料表*/
--UPDATE STOCK_NAME_SERIAL SET SERIAL=B.SERIAL
--FROM STOCK_NAME_SERIAL A INNER JOIN @SERIAL B ON A.SYMBOL=B.SYMBOL
