SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		chen 
-- Create date: 2021.3.18
-- Description:	禦秈布
-- =============================================
/*
DECLARE @ERRMSG	VARCHAR(1000)
EXEC PROC_BUY_STOCK '2021/1/15',2330,'585H1234567',1500,@ERRMSG OUTPUT
PRINT @ERRMSG
SELECT * FROM STOCK_DEAL
*/
create or alter PROCEDURE PROC_BUY_STOCK--ユ把计
@DATE date,--ユら戳
@SYMBOL	varchar(10),--布腹
@TDCCACCOUNT	varchar(20),--栋玂眀腹
@QTY	decimal(20,4),--禦秈秖
@ERRMSG	varchar(1000) output--岿粇癟
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;
	IF NOT EXISTS(SELECT * FROM STOCK_NAME_FULL WHERE SYMBOL=@SYMBOL)
	BEGIN
		SELECT @ERRMSG='布腹ぃ'
		RETURN;
	END;

	--眔程腹
	DECLARE @MAXNO	VARCHAR(20)
	DECLARE @SERIAL VARCHAR(20)
	SELECT @MAXNO=ISNULL(MAX(SERIAL),'190001010000') FROM STOCK_DEAL
	SELECT @MAXNO=CONVERT(VARCHAR(20),CONVERT(INT,RIGHT(@MAXNO,4))+1)
	SELECT @MAXNO=RIGHT('0000'+@MAXNO,4)
	SELECT @SERIAL=CONVERT(VARCHAR(10),@DATE,112)+@MAXNO
	--眔布秨絃基
	DECLARE @PRICE DECIMAL(20,4)
	SELECT @PRICE=[OPEN]
	FROM STOCK_PRICE
	WHERE DATE=@DATE AND SYMBOL=@SYMBOL
	DECLARE @myfee DECIMAL(20,4)
	Select @myfee= CASE WHEN ROUND(@PRICE*@QTY*0.01,0)<=100000 THEN ROUND(@PRICE*@QTY*0.01,0) ELSE ROUND(@PRICE*@QTY*0.005,0) END 
	--璶干
	IF NOT EXISTS(SELECT * FROM STOCK_PRICE WHERE  DATE=@DATE and SYMBOL=@SYMBOL    )
	BEGIN
		SELECT @ERRMSG='礚基癟'
		RETURN;
	END;

	BEGIN TRAN
	BEGIN TRY
	
		INSERT STOCK_DEAL --insertDEAL
		(
		SERIAL,DATE,SYMBOL,TDCCACCOUNT,DATATYPE,
		QTY,PRICE,AMT,FEE,TAX,
		TOTALAMT,
		LOGDATE
		)

		SELECT @SERIAL AS SERIAL,@DATE AS [DATE],@SYMBOL AS SYMBOL,@TDCCACCOUNT AS TDCCACCOUNT,1 AS DATATYPE,
		@QTY AS QTY,@PRICE AS PRICE,ROUND(@PRICE*@QTY,0) AS AMT,
		@myfee AS FEE, -- 硂娩耞琌禬筁10窾
		ROUND(@PRICE*@QTY*0.003,0) AS TAX,
		ROUND(@PRICE*@QTY,0)+
		@myfee+
		ROUND(@PRICE*@QTY*0.003,0) AS TOTALAMT,
		GETDATE() AS LOGDATE


		COMMIT
	END TRY
	BEGIN CATCH
		ROLLBACK
		SELECT @ERRMSG=ERROR_MESSAGE()
	END CATCH
END
GO
